---
config:
  mirrorActors: false
  theme: base
  themeVariables:
    primaryColor: "#f3f2f1"
    fontSize: 24px 
    noteBkgColor: "#f3f2f1"  
---
﻿﻿sequenceDiagram
  autonumber
  participant S as Your service
  participant OL as GOV.UK One Login
  Note over S,OL: Retrieve OIDC metadata
  S->>+OL: GET /.well-known/openid-configuration
  OL-->>-S: Discovery document as JSON 
  Note over S,OL: Authorise
  S->>S: Create request JWT and <br/>sign with private key
  S->>+OL: GET /authorize (including request parameter)
  OL->>S: Fetches public key:<br/>GET JWKS endpoint
  S-->>OL: Return public key as JWKS document
  OL->>OL: Validate authorize request
  OL->>OL: The user logs in or creates an account<br/>and optionally proves their identity
  OL-->>-S: HTTP 302 redirect (including authorisation code)
  Note over S,OL: Exchange authorisation code for an <br/>access token and ID token
  S->>S: Create request JWT and <br/>sign with private key
  S->>OL: POST /token (including authorisation code and assertion)
  OL->>S: Fetches public keys:<br/>GET JWKS endpoint
  S-->>OL: Return public keys as JWKS document
  OL->>OL: Verify token request
  OL-->>S: ID Token and access token
  S->>OL: Fetch public keys<br/>GET /.well-known/jwks.json
  OL-->>S: Returns public keys as JWKS document 
  S->>S: Validate ID token signature with public key
  Note over S,OL: Retrieve userinfo 
  S->>OL: GET /userinfo (including access token)
  OL-->>S: userinfo (including core identity claim)
  S->>OL: Fetch public keys:<br/>GET /.well-known/did.json
  OL-->>S: Returns public keys in DID document
  S->>S: Validate signature of<br/>core identity claim<br/>with public key 