name: Check pull request
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  check-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@bec3f19a76460dbe12f60def7d1a77585f07516c # pin@v1
        with:
          bundler-cache: true
      - name: Build
        run: bundle exec middleman build --verbose
